services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: agno-rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  wren-engine:
      image: ghcr.io/canner/wren-engine:latest
      ports:
        - "8081:8080"
      environment:
        - SAMPLE_DB_URL=sqlite+aiosqlite:///wren_sample.db
      volumes:
        - ./etc:/usr/src/app/etc
      restart: unless-stopped

  ibis-server:
      image: ghcr.io/canner/wren-engine-ibis:latest
      ports:
        - "8000:8000"
      environment:
        - WREN_ENGINE_ENDPOINT=http://wren-engine:8080
      volumes:
        - ./etc:/usr/src/app/etc
      restart: unless-stopped



volumes:
  qdrant_storage:
    driver: local
